// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var en_textMTH, en_textmth, jp_textMTH, jp_textmth;
    en_textMTH = (function() {

      /*
      		English
       */
      function en_textMTH(className) {
        this.className = className;
        this._decorateFunc();
        this._setAddClass();
      }

      en_textMTH.prototype._decorateFunc = function() {
        $(this.className).children().addBack().contents().each(function() {
          if (this.nodeType === 3) {
            $(this).replaceWith($(this).text().replace(/(\w)/g, "<span>$&</span>"));
          }
        });
      };

      en_textMTH.prototype._setAddClass = function() {
        var num;
        num = 0;
        return $(this.className).each(function() {
          $("span", this).each(function(i) {
            num = num + 1;
            $(this).addClass("type-0" + num);
            if (4 === num) {
              num = 1;
            }
          });
        });
      };

      return en_textMTH;

    })();
    jp_textMTH = (function() {

      /*
      		Japanese
       */
      function jp_textMTH(className) {
        this.className = className;
        this._decorateFunc();
        this._setAddClass();
      }

      jp_textMTH.prototype._decorateFunc = function() {
        var $counter, $mthString, _results;
        $(this.className).after('<p class="js-inner"></p>');
        $(this.className).hide();
        $mthString = $(this.className).text();
        $counter = 0;
        _results = [];
        while ($counter < $mthString.length) {
          $(".js-inner").append('<span class="type-01">' + $mthString.charAt($counter) + '</span>');
          _results.push($counter++);
        }
        return _results;
      };

      jp_textMTH.prototype._setAddClass = function() {
        var num;
        num = 0;
        return $(".js-inner").each(function() {
          $("span", this).each(function(i) {
            num = num + 1;
            $(this).addClass("type-0" + num);
            if (4 === num) {
              num = 1;
            }
          });
        });
      };

      return jp_textMTH;

    })();
    jp_textmth = new jp_textMTH(".jp-mth-text");
    return en_textmth = new en_textMTH(".en-mth-text");
  });

}).call(this);
